apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-frontend
  labels:
    app: springboot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-frontend
  template:
    metadata:
      labels:
        app: springboot-frontend
    spec:
      containers:
        - name: springboot-frontend
          image: shakilsaddam/springboot-mysql
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          #MountPath is based on AnjayBRD project. It has to be changed in other applications.
          #volumeMounts:
          #  - name: persistent-storage-springboot
          #    mountPath: /User/File/TimeSheet/files/
      
      #volumes:
      #  - name: persistent-storage-springboot
      #    persistentVolumeClaim:
      #      claimName: springboot-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-frontend-svc
  labels:
    name: springboot-frontend-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8080
      nodePort: 30081
  selector:
    app: springboot-frontend